common: &common
  adapter: postgresql
  username: etsydemo
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: etsydemo_development

test:
  <<: *common
  database: etsydemo_test

production:
  <<: *common
  database: etsydemo_production